In [39]:
import pandas as pd
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [40]:
df.drop(["PassengerId", "Name", "SibSp", "Parch", "Ticket", "Cabin", "Embarked"], axis = 'columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [41]:
target = df.Survived
inputs = df.drop("Survived",axis = "columns")

In [42]:
dummies = pd.get_dummies(inputs.Sex,dtype = int )
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [43]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [44]:
inputs.drop("Sex", axis = "columns", inplace =True)
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [45]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='str')

In [46]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [47]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2)

In [49]:
len(X_train)

712

In [50]:
len(X_test)

179

In [51]:
len(inputs)

891

In [52]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [53]:
model.fit(X_train, y_train)

GaussianNB()

In [54]:
model.score(X_test,y_test )

0.8212290502793296

In [55]:
X_test[:10]

     Pclass   Age     Fare  female  male
345       2  24.0  13.0000       1     0
728       2  25.0  26.0000       0     1
331       1  45.5  28.5000       0     1
665       2  32.0  73.5000       0     1
518       2  36.0  26.0000       1     0
13        3  39.0  31.2750       0     1
15        2  55.0  16.0000       1     0
97        1  23.0  63.3583       0     1
456       1  65.0  26.5500       0     1
504       1  16.0  86.5000       1     0

In [56]:
y_test[:10]

345    1
728    0
331    0
665    0
518    1
13     0
15     1
97     1
456    0
504    1
Name: Survived, dtype: int64

In [57]:
model.predict(X_test[:10])

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [58]:
model.predict_proba(X_test[:10])

array([[0.03478775, 0.96521225],
       [0.9740184 , 0.0259816 ],
       [0.92216772, 0.07783228],
       [0.92546342, 0.07453658],
       [0.03758309, 0.96241691],
       [0.98855267, 0.01144733],
       [0.03243234, 0.96756766],
       [0.83007752, 0.16992248],
       [0.88397552, 0.11602448],
       [0.00141692, 0.99858308]])